#!/bin/bash
set -e

# I want a git worktree(wt) util to help me create delete lock
# also need bash complete

# usage
# git wt add <branch> name
# git wt delete name
# git wt ls
# git wt cd name

# reference
#   https://github.com/yankeexe/git-worktree-switcher

# TODO
# bash completion
# USAGE

USAGE="usage: git wt [add|delete|ls|cd] ..."

if [ $# -lt 1 ]; then
    echo "$USAGE"
    exit 1
fi

basePath=$(git worktree list | awk '{print $1}' | sort | head -1)

if [[ $1 == "add" && $# -eq 3 ]]; then
    git worktree add "${basePath}_$2" "$3"
    # copy noevim project level config
    if [ -e "${basePath}/.nvim.lua" ]; then
        # -R to preserve symbolic links
        cp -R "${basePath}/.nvim.lua" "${basePath}_$2/.nvim.lua"
        echo "copy ${basePath}/.nvim.lua to ${basePath}_$2/.nvim.lua"
    fi
    echo "run the following command to enter the worktree"
    echo
    echo "wco $2"
    echo
elif [[ "$1" == "delete" && $# -eq 2 ]]; then
    cd "${basePath}_$2"

    # check files
    # TODO: add -f optional to force delete all the files
    if [[ $(git status --porcelain) ]]; then
        echo "worktree has untracked/uncommit files, please remove/commit them"
        exit 1
    fi

    git worktree remove "${basePath}_$2"

    echo "run the following command to enter the root worktree"
    echo
    echo "cd ${basePath}"
    echo
elif [[ $1 == "ls" && $# -eq 1 ]]; then
    git worktree list
elif [[ $1 == "cd" ]]; then
    echo "use wco instead"
else
    echo "$USAGE"
    exit 1
fi
