#! /bin/bash
# all customized function collect at this file

dCount() {

    find "$1" -type d -print0 | while read -d '' -r dir; do
        files=("$dir"/*)
        printf "%5d files in directory %s\n" "${#files[@]}" "$dir"
    done
}

dirdiff() {
    # Shell-escape each path:
    DIR1=$(printf '%q' "$1")
    shift
    DIR2=$(printf '%q' "$1")
    shift
    vim "$@" -c "DirDiff $DIR1 $DIR2"
}

create_venv() {
    if [ ! -d ~/venv/ ]; then
        echo "Creating ~/venv/ for python venv"
        mkdir ~/venv/
    fi
}

venv() {
    # specified which venv will be used
    if [ -e ~/venv/"$1"/bin/activate ]; then
        . ~/venv/"$1"/bin/activate
        return 0
    fi

    # recursively to find venv in the current working directory
    p='-' # any string as init
    until [ "$p" == '/' ]; do
        if [ "$p" == '-' ]; then # init as
            p=$PWD
        else
            p=$(dirname "$p")
        fi

        #echo $p
        #echo ${p##*/}

        if [ -e ~/venv/"${p##*/}"/bin/activate ]; then
            . ~/venv/"${p##*/}"/bin/activate
            break
        fi
    done
}
export -f venv

nonascii() {
    LANG=C rg -P '[^\x00-\x7f]'
}

showOS() {
    unameOut="$(uname -s)"
    case "$unameOut" in
    Linux*) awk -F= '/^NAME/{print $2}' /etc/os-release ;;
    Darwin*) echo Mac ;;
    *)
        echo "UNKNOWN:${unameOut}"
        ;;
    esac
    uname -m
}

checksum() {
    echo md5
    md5sum "$1"
    echo sha1
    sha1sum "$1"
    echo sha256
    sha256sum "$1"
}

# git worktree co [worktree name]
wco() {
    target=$(git worktree list | awk '{print $1}' | sort | head -1)
    if [ $# -ne 0 ]; then
        target="${target}_$1"
    fi

    tmpfile=$(mktemp)
    echo "#!/bin/bash" >"$tmpfile"
    echo "cd $target" >>"$tmpfile"
    . "$tmpfile" # do the cd
    echo "cd $target"
    rm -f -- "$tmpfile"
}


