
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac


# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# add alais
unalias -a
alias ls='ls -GFh'
alias ll='ls -al'
alias la='ls -a'
alias l='la'
alias grep='grep --color=auto'
alias rm='rm -i'
alias pdb='python -m pdb'
alias medit='markdown_edit'
alias v='vim'
alias p='python'
alias vd='vimdiff'
alias tree='tree -N'

#alias readlink='greadlink -f'

color_prompt=yes

# add git completed
source ~/.git-completion.bash
source ~/.git-prompt.sh

# set git prompt
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWUPSTREAM="auto"
GIT_PS1_SHOWCOLORHINTS="yes"
GIT_PS1_SHOWUNTRACKEDFILES=true

# set PS1 color
# '\u'=user, 'h'=host name, '\w'=full path
#                     30=Black, 31=Red, 32=Green, 33=Yellow, 34=Blue, 35=Purple, 36=Cyan, 37=White
# Bold High Intensity 90=Black, 91=Red, 92=Green, 93=Yellow, 94=Blue, 95=Purple, 96=Cyan, 97=White
# 0=Regular, 1=Bold, 4=Underline
# reference : https://wiki.archlinux.org/index.php/Color_Bash_Prompt
export PS1="\[\033[0;36m\]\u\[\033[m\]@\[\033[0;32m\]\h\[\033[m\]:\[\033[1;33m\]\w \[\033[1;35m\]\$(__git_ps1 '(%s)')\[\033[m\]\$ "

#set show-all-if-ambiguous on
bind '"\e[Z":menu-complete' # Shift-Tab auto complete

# fzf
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'

export LC_ALL=en_US.UTF-8

. ~/.util.mrg

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  --no-use  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion


## The next line updates PATH for the Google Cloud SDK.
#if [ -f '/usr/local/google-cloud-sdk/path.bash.inc' ]; then . '/usr/local/google-cloud-sdk/path.bash.inc'; fi
#
## The next line enables shell command completion for gcloud.
#if [ -f '/usr/local/google-cloud-sdk/completion.bash.inc' ]; then . '/usr/local/google-cloud-sdk/completion.bash.inc'; fi
#
## google compute engine ssh shortcut
#alias sshg='gcloud beta compute ssh --project "long-loop-247502" --zone "us-west1-b" "ggg77599@google-vm"'
#
