#!/bin/sh

echo "Add 'GIT_HOOKS_SKIP=1' in front of command to SKIP check"

if [[ (! -z ${GIT_HOOKS_SKIP} ) && ${GIT_HOOKS_SKIP}=1 ]]; then
  echo "GIT_HOOKS_SKIP pre-commit"
  exit 0
fi

# Check if we are on master branch
#if test $(git rev-parse --abbrev-ref HEAD) = "master" ; then
#if test $(git branch --show-current) = "master" ; then
#  echo "Cannot commit on master"
#  exit 1
#fi

#if test $(git branch --show-current) = "main" ; then
#  echo "Cannot commit on main"
#  exit 1
#fi

# Run local pre-commit hook if exists
echo "Run local pre-commit hook if exists"
if [ -e ./.git/hooks/pre-commit ]; then
  ./.git/hooks/pre-commit "$@"
else
  exit 0
fi

